import type { StyleId, StylePreset } from "./types.ts";

export const STYLES: Record<StyleId, StylePreset> = {
  signature: {
    id: "signature",
    name: "Signature",
    blurb: "Large amplitude, slow up, fast down, organic cadence, holds on rest.",
    minPos: 8,
    maxPos: 94,
    upPoints: 3,
    downPoints: 1,
    cadenceSkip: 0.18,
    pauseThreshold: 0.11,
    minHoldMs: 220,
    prominence: 0.07,
    smoothing: 0.4,
  },
  mechanical: {
    id: "mechanical",
    name: "Mechanical",
    blurb: "Full range, even strokes, every peak kept. Useful as a raw draft.",
    minPos: 5,
    maxPos: 95,
    upPoints: 0,
    downPoints: 0,
    cadenceSkip: 0,
    pauseThreshold: 0.08,
    minHoldMs: 140,
    prominence: 0.055,
    smoothing: 0.25,
  },
  soft: {
    id: "soft",
    name: "Soft",
    blurb: "Mid-range travel, gentler peaks, longer holds. Less fatigue.",
    minPos: 18,
    maxPos: 78,
    upPoints: 2,
    downPoints: 2,
    cadenceSkip: 0.22,
    pauseThreshold: 0.14,
    minHoldMs: 280,
    prominence: 0.09,
    smoothing: 0.55,
  },
  dense: {
    id: "dense",
    name: "Dense",
    blurb: "High action count. Captures small motions. Expect more cleanup.",
    minPos: 6,
    maxPos: 96,
    upPoints: 1,
    downPoints: 1,
    cadenceSkip: 0.04,
    pauseThreshold: 0.07,
    minHoldMs: 120,
    prominence: 0.04,
    smoothing: 0.22,
  },
};

export const STYLE_LIST: StylePreset[] = [
  STYLES.signature,
  STYLES.mechanical,
  STYLES.soft,
  STYLES.dense,
];
